/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './modules/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          bg:      '#090A0F',
          panel:   '#141824',
          card:    '#111420',
          sidebar: '#0B0D13',
          border:  '#1A1E2C',
          divider: '#212636',
          elevated:'#181C28',
        },
        text: {
          primary:   '#F1F3F9',
          secondary: '#8B92A5',
          muted:     '#525B72',
          disabled:  '#3A4155',
        },
        accent: {
          purple:     '#7C3AED',
          'purple-mid': '#8B5CF6',
          'purple-soft': '#A78BFA',
          blue:       '#2563EB',
          'blue-soft':'#60A5FA',
          green:      '#059669',
          'green-soft':'#34D399',
          amber:      '#D97706',
          'amber-soft':'#FCD34D',
          red:        '#DC2626',
          'red-soft': '#F87171',
        },
      },
      borderRadius: {
        sm:     '4px',
        DEFAULT:'6px',
        md:     '8px',
        lg:     '10px',
        xl:     '12px',
        '2xl':  '16px',
        '3xl':  '20px',
        input:  '8px',
        button: '8px',
        card:   '12px',
        dialog: '14px',
        badge:  '9999px',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'Inter', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Cascadia Code', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.625rem',  { lineHeight: '1rem' }],
        'xs':  ['0.75rem',   { lineHeight: '1.125rem' }],
        'sm':  ['0.8125rem', { lineHeight: '1.25rem' }],
        'base':['0.875rem',  { lineHeight: '1.375rem' }],
        'lg':  ['1rem',      { lineHeight: '1.5rem' }],
        'xl':  ['1.125rem',  { lineHeight: '1.625rem' }],
        '2xl': ['1.25rem',   { lineHeight: '1.75rem' }],
        '3xl': ['1.5rem',    { lineHeight: '2rem' }],
      },
      boxShadow: {
        sm:     '0 1px 3px rgba(0,0,0,0.4), 0 1px 2px rgba(0,0,0,0.3)',
        md:     '0 4px 16px rgba(0,0,0,0.5), 0 2px 8px rgba(0,0,0,0.3)',
        lg:     '0 12px 40px rgba(0,0,0,0.6), 0 4px 16px rgba(0,0,0,0.4)',
        xl:     '0 24px 60px rgba(0,0,0,0.7), 0 8px 24px rgba(0,0,0,0.5)',
        subtle: '0 2px 8px rgba(0,0,0,0.25)',
        dialog: '0 24px 60px rgba(0,0,0,0.7)',
        purple: '0 4px 16px rgba(124,58,237,0.35)',
        glow:   '0 0 20px rgba(124,58,237,0.25)',
      },
      animation: {
        'fade-in':     'fadeIn 0.2s ease-out',
        'slide-up':    'slideUp 0.25s ease-out',
        'slide-down':  'slideDown 0.25s ease-out',
        'slide-right': 'slideRight 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
        'slide-left':  'slideLeft 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
        'scale-in':    'scaleIn 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
        'shimmer':     'shimmer 1.8s ease-in-out infinite',
        'spin-slow':   'spin 2s linear infinite',
        'bounce-sm':   'bounceSm 1s ease-in-out infinite',
        'pulse-slow':  'pulse 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:    { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp:   { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideRight:{ from: { transform: 'translateX(100%)' }, to: { transform: 'translateX(0)' } },
        slideLeft: { from: { transform: 'translateX(-100%)' }, to: { transform: 'translateX(0)' } },
        scaleIn:   { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        shimmer: {
          '0%':   { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        bounceSm: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':      { transform: 'translateY(-3px)' },
        },
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'bounce': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      spacing: {
        '13': '52px',
        '15': '60px',
        '18': '72px',
        '22': '88px',
        '68': '272px',
        '72': '288px',
        '76': '304px',
        '80': '320px',
      },
      zIndex: {
        '60':  '60',
        '70':  '70',
        '80':  '80',
        '90':  '90',
        '100': '100',
        '200': '200',
      },
      screens: {
        'xs': '480px',
        '3xl': '1920px',
      },
      backdropBlur: {
        xs: '2px',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
    },
  },
  plugins: [],
};
